Composition {
	CurrentTime = 0,
	RenderRange = { 0, 0 },
	GlobalRange = { 0, 1 },
	CurrentID = 3311,
	HiQ = true,
	PlaybackUpdateMode = 0,
	Version = "Fusion 9.0.1 build 3",
	SavedOutputs = 1,
	HeldTools = 0,
	DisabledTools = 0,
	LockedTools = 0,
	AudioOffset = 0,
	Resumable = true,
	OutputClips = {
		"/home/pp/projects/pypoks/gui/cards/dfR/TC.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/4C.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/8H.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/7C.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/3S.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/KS.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/TS.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/7S.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/6C.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/REV.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/8D.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/JS.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/2S.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/JH.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/2H.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/6H.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/AH.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/5H.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/4S.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/6S.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/6D.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/4D.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/TH.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/8C.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/9C.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/3D.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/3H.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/DS.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/9D.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/8S.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/5S.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/TD.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/KH.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/AS.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/DD.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/5C.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/JC.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/KC.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/2D.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/5D.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/JD.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/3C.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/4H.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/DH.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/KD.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/AD.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/DC.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/7H.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/2C.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/9S.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/7D.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/9H.png",
		"/home/pp/projects/pypoks/gui/cards/dfR/AC.png"
	},
	Tools = {
		Loader1 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/home/pp/projects/pypoks/gui/cards/4h-3d-2s-ac.png",
					FormatID = "PNGFormat",
					StartFrame = -1,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 0,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 0,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 0
				}
			},
			Inputs = {
				["Clip1.PNGFormat.PostMultiply"] = Input { Value = 1, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { -55, -49.5 } },
		},
		Loader5 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/home/pniewinski/projects/pypoks_evo/images/pypoks_logo_alph_black.png",
					FormatID = "PNGFormat",
					StartFrame = -1,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 0,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 0,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 0
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 110, -610.5 } },
		},
		Loader3 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/home/pp/projects/pypoks/pypoks.png",
					FormatID = "PNGFormat",
					StartFrame = -1,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 0,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 0,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 0
				}
			},
			Inputs = {
				["Clip1.PNGFormat.PostMultiply"] = Input { Value = 1, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { -275, -577.5 } },
		},
		Loader2 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/home/pp/projects/pypoks/pypoks.png",
					FormatID = "PNGFormat",
					StartFrame = -1,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 0,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 0,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 0
				}
			},
			Inputs = {
				["Clip1.PNGFormat.PostMultiply"] = Input { Value = 1, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				EffectMask = Input {
					SourceOp = "Rectangle3",
					Source = "Mask",
				}
			},
			ViewInfo = OperatorInfo { Pos = { -935, 214.5 } },
		},
		Loader4 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/home/pp/projects/pypoks/gui/user-icon-male-person-symbol-profile-avatar-vector-20787339.jpg",
					FormatID = "JpegFormat",
					StartFrame = 20787339,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 0,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 0,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 0
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { -440, -412.5 } },
		},
		Loader7 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "/home/pniewinski/projects/pypoks_evo/images/pypoks_logo_alph_white_add.png",
					FormatID = "PNGFormat",
					StartFrame = -1,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 0,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 0,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 0
				}
			},
			CtrlWZoom = false,
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 385, -610.5 } },
		},
		Instance_Crop1_3_1_7 = Crop {
			SourceOp = "Instance_Crop1_2_1_7",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_3_7",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1765.5 } },
		},
		Text1_1_1_4 = TextPlus {
			Inputs = {
				HorizontalJustificationNew = Input { Value = 3, },
				VerticalJustificationNew = Input { Value = 3, },
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				Center = Input { Value = { 0.5, 0.545083011716293 }, },
				Font = Input { Value = "DejaVu Sans", },
				StyledText = Input { Value = "6", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Alignment = Input { Value = 1, },
				HorizontalJustification = Input { Value = 1, },
				Red1 = Input { Value = 0.778792858123779, },
				Green1 = Input { Value = 0.0274509191513062, },
				Blue1 = Input { Value = 0.0961014628410339, },
			},
			ViewInfo = OperatorInfo { Pos = { -825, 1006.5 } },
		},
		Merge3_2_1_3_3 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2_3",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_3",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.354255561468705 }, },
				Size = Input { Value = 0.883932231992637, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 110, 940.5 } },
		},
		Merge4_1_1_2_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_4",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 577.5 } },
		},
		Instance_Crop1_2_1_11 = Crop {
			Inputs = {
				XOffset = Input { Value = 56, },
				YOffset = Input { Value = 60, },
				XSize = Input { Value = 108, },
				YSize = Input { Value = 180, },
				KeepCentered = Input { Value = 1, },
				Input = Input {
					SourceOp = "Merge3_2_1_1_1_11",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 220, 2359.5 } },
		},
		Instance_Transform4_2 = Transform {
			SourceOp = "Transform4",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				TransformNest = Input { },
				ReferenceSize = Input { },
				Input = Input {
					SourceOp = "Merge1",
					Source = "Output",
				},
				EffectMask = Input { }
			},
			ViewInfo = OperatorInfo { Pos = { 0, 148.5 } },
		},
		Instance_Crop1_1_1_10 = Crop {
			SourceOp = "Instance_Crop1_2_1_10",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_2_1_10",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 2161.5 } },
		},
		Polygon1Polyline = BezierSpline {
			SplineColor = { Red = 173, Green = 255, Blue = 47 },
			NameSet = true,
			KeyFrames = {
				[0] = { 0, Flags = { Linear = true, LockedY = true }, Value = Polyline {
						Closed = true,
						Points = {
							{ Linear = true, X = -0.456289978296772, Y = 0.209677418817605, LX = 0.000553238260551129, LY = -0.0625778870241201, RX = 0.0355879229989218, RY = -0.0021463732961459 },
							{ Linear = true, X = -0.349526209300007, Y = 0.203238298929167, LX = -0.0355879229989218, LY = 0.0021463732961459, RX = 0.024468932769446, RY = -0.0218890476347449 },
							{ Linear = true, X = -0.276119410991669, Y = 0.137571156024933, LX = -0.024468932769446, LY = 0.0218890476347449, RX = 0.0234541604513807, RY = 0.0183428214894753 },
							{ Linear = true, X = -0.205756932497025, Y = 0.19259962439537, LX = -0.0234541604513807, LY = -0.0183428214894753, RX = 0.0611229575985107, RY = 0.00189753190616049 },
							{ Linear = true, X = -0.0223880596458912, Y = 0.198292225599289, LX = -0.0611229575985107, LY = -0.00189753190616049, RX = 0.0906183368684598, RY = 0 },
							{ Linear = true, X = 0.249466955661774, Y = 0.198292225599289, LX = -0.0906183368684598, LY = 0, RX = 0, RY = -0.0910815957563727 },
							{ Linear = true, X = 0.249466955661774, Y = -0.0749525651335716, LX = 0, LY = 0.0910815957563727, RX = -0.232054017203534, RY = -0.00442757632802515 },
							{ Linear = true, X = -0.44669508934021, Y = -0.0882352963089943, LX = 0.232054017203534, LY = 0.00442757632802515, RX = -0.00264505805830288, RY = 0.036726351351413 },
							{ Linear = true, X = -0.454630263515119, Y = 0.0219437577452447, LX = 0.00264505805830288, LY = -0.036726351351413, RX = -0.000553238260551129, RY = 0.0625778870241201 }
						}
					} }
			}
		},
		Instance_Crop1_4_1 = Crop {
			SourceOp = "Instance_Crop1_2_1_1",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_2_1",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 577.5 } },
		},
		Merge8 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge7",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Background4_1_1_1",
					Source = "Output",
				},
				PerformDepthMerge = Input { Value = 0, },
				EffectMask = Input {
					SourceOp = "Ellipse3_1_1",
					Source = "Mask",
				}
			},
			ViewInfo = OperatorInfo { Pos = { -275, -379.5 } },
		},
		Polygon4Polyline = BezierSpline {
			SplineColor = { Red = 173, Green = 255, Blue = 47 },
			NameSet = true,
			KeyFrames = {
				[0] = { 0, Flags = { Linear = true, LockedY = true }, Value = Polyline {
						Closed = true,
						Points = {
							{ Linear = true, X = -0.220494707948507, Y = 0.236124824271834, LX = 0.00127714524731391, LY = -0.157016956404261, RX = 0.0206852693667931, RY = 0.0138399281690467 },
							{ Linear = true, X = -0.158438899848127, Y = 0.277644608778974, LX = -0.0206852693667931, LY = -0.0138399281690467, RX = 0.106844854121769, RY = -3.00239007162695e-05 },
							{ Linear = true, X = 0.16209566251718, Y = 0.277554537076825, LX = -0.106844854121769, LY = 3.00239007162695e-05, RX = 0.0175646623896441, RY = -0.0133138821684052 },
							{ Linear = true, X = 0.214789649686112, Y = 0.23761289057161, LX = -0.0175646623896441, LY = 0.0133138821684052, RX = 0.000674642976327614, RY = -0.158040815975438 },
							{ Linear = true, X = 0.216813578615095, Y = -0.236509557354705, LX = -0.000674642976327614, LY = 0.158040815975438, RX = -0.0184643029819934, RY = -0.0133772924612277 },
							{ Linear = true, X = 0.161420669669115, Y = -0.276641434738388, LX = 0.0184643029819934, LY = 0.0133772924612277, RX = -0.10833973751744, RY = 0.000694295655447578 },
							{ Linear = true, X = -0.163598542883205, Y = -0.274558547772045, LX = 0.10833973751744, LY = -0.000694295655447578, RX = -0.0176882431077868, RY = 0.0132108342770323 },
							{ Linear = true, X = -0.216663272206565, Y = -0.234926044940948, LX = 0.0176882431077868, LY = -0.0132108342770323, RX = -0.00127714524731391, RY = 0.157016956404261 }
						}
					} }
			}
		},
		Merge4_1_3_3 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "ColorCorrector1_2_3",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 841.5 } },
		},
		Merge3_2_2 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_2",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.336847437677603 }, },
				Size = Input { Value = 0.949970674486804, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 0, 412.5 } },
		},
		Instance_Crop1_2_1_1 = Crop {
			Inputs = {
				XOffset = Input { Value = 56, },
				YOffset = Input { Value = 60, },
				XSize = Input { Value = 108, },
				YSize = Input { Value = 180, },
				KeepCentered = Input { Value = 1, },
				Input = Input {
					SourceOp = "Merge3_2_1_1_1_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 220, 544.5 } },
		},
		Instance_Transform4_7 = Transform {
			SourceOp = "Transform4",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				TransformNest = Input { },
				ReferenceSize = Input { },
				Input = Input {
					SourceOp = "Text1_1_1_4",
					Source = "Output",
				},
				EffectMask = Input { }
			},
			ViewInfo = OperatorInfo { Pos = { -715, 1006.5 } },
		},
		Instance_Scale1_1_1_9 = Scale {
			SourceOp = "Instance_Scale1_2_1_9",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_1_1_9",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1996.5 } },
		},
		Merge3_2_1_1_1_7 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3_7",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_1",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.34458438158476 }, },
				Size = Input { Value = 0.961301671064204, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -110, 1699.5 } },
		},
		Instance_Background4 = Background {
			SourceOp = "Background4",
			Inputs = {
				ImageNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				BackgroundNest = Input { },
				CommentsNest = Input { },
				["Gamut.ColorSpaceNest"] = Input { },
				["Gamut.GammaSpaceNest"] = Input { },
				EffectMask = Input {
					SourceOp = "Ellipse2",
					Source = "Mask",
				}
			},
			ViewInfo = OperatorInfo { Pos = { -330, -214.5 } },
		},
		Text1_1_1_9 = TextPlus {
			Inputs = {
				HorizontalJustificationNew = Input { Value = 3, },
				VerticalJustificationNew = Input { Value = 3, },
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				Center = Input { Value = { 0.5, 0.545083011716293 }, },
				Font = Input { Value = "DejaVu Sans", },
				StyledText = Input { Value = "D", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Alignment = Input { Value = 1, },
				HorizontalJustification = Input { Value = 1, },
				Red1 = Input { Value = 0.778792858123779, },
				Green1 = Input { Value = 0.0274509191513062, },
				Blue1 = Input { Value = 0.0961014628410339, },
			},
			ViewInfo = OperatorInfo { Pos = { -825, 1996.5 } },
		},
		Instance_Scale1_4_11 = Scale {
			SourceOp = "Instance_Scale1_2_1_11",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_4_11",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 2392.5 } },
		},
		Instance_Scale1_4_1 = Scale {
			SourceOp = "Instance_Scale1_2_1_1",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_4_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 577.5 } },
		},
		Merge3_2_1_1_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_1",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.34458438158476 }, },
				Size = Input { Value = 0.961301671064204, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -110, 379.5 } },
		},
		Instance_Crop1_3 = Crop {
			SourceOp = "Crop1",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1600.5 } },
		},
		Merge4_1_1_2_11 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_15",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 2392.5 } },
		},
		ColorCorrector1_2_9 = ColorCorrector {
			Inputs = {
				WheelSaturation1 = Input { Value = 0, },
				MasterRGBGain = Input { Value = 0, },
				ColorRanges = Input {
					Value = ColorCurves {
						Curves = {
							{
								Points = {
									{ 0, 1 },
									{ 0.4, 0.2 },
									{ 0.6, 0 },
									{ 1, 0 }
								}
							},
							{
								Points = {
									{ 0, 0 },
									{ 0.4, 0 },
									{ 0.6, 0.2 },
									{ 1, 1 }
								}
							}
						}
					},
				},
				HistogramIgnoreTransparent = Input { Value = 1, },
				Input = Input {
					SourceOp = "Instance_Transform4_13",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -605, 1996.5 } },
		},
		Saver1_2_1_7 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/TC.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_2_1_7",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1699.5 } },
		},
		Merge3_2_1_3_10 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2_10",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_3",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.354255561468705 }, },
				Size = Input { Value = 0.883932231992637, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 110, 2260.5 } },
		},
		Merge3_2_1_3_7 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2_7",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_3",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.354255561468705 }, },
				Size = Input { Value = 0.883932231992637, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 110, 1765.5 } },
		},
		Instance_Crop1_2_1_3 = Crop {
			Inputs = {
				XOffset = Input { Value = 56, },
				YOffset = Input { Value = 60, },
				XSize = Input { Value = 108, },
				YSize = Input { Value = 180, },
				KeepCentered = Input { Value = 1, },
				Input = Input {
					SourceOp = "Merge3_2_1_1_1_3",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 220, 874.5 } },
		},
		Instance_Transform4_8 = Transform {
			SourceOp = "Transform4",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				TransformNest = Input { },
				ReferenceSize = Input { },
				Input = Input {
					SourceOp = "Text1_1_1_5",
					Source = "Output",
				},
				EffectMask = Input { }
			},
			ViewInfo = OperatorInfo { Pos = { -715, 1171.5 } },
		},
		Merge3_2_1_2_1_6 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3_6",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.348452853538338 }, },
				Size = Input { Value = 0.864555848724714, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -220, 1336.5 } },
		},
		Instance_Scale1 = Scale {
			SourceOp = "Scale1",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1567.5 } },
		},
		Merge10 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge9",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader3",
					Source = "Output",
				},
				Center = Input { Value = { 0.650537634408602, 0.28494623655914 }, },
				Size = Input { Value = 0.0494254032258064, },
				ApplyMode = Input { Value = FuID { "Multiply" }, },
				PerformDepthMerge = Input { Value = 0, },
				EffectMask = Input {
					SourceOp = "Polygon5",
					Source = "Mask",
				}
			},
			ViewInfo = OperatorInfo { Pos = { -55, -379.5 } },
		},
		Instance_Crop1_2_1_2 = Crop {
			Inputs = {
				XOffset = Input { Value = 56, },
				YOffset = Input { Value = 60, },
				XSize = Input { Value = 108, },
				YSize = Input { Value = 180, },
				KeepCentered = Input { Value = 1, },
				Input = Input {
					SourceOp = "Merge3_2_1_1_1_2",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 220, 709.5 } },
		},
		Merge6 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background4",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text1",
					Source = "Output",
				},
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -220, -247.5 } },
		},
		Instance_Transform4 = Transform {
			SourceOp = "Transform4",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				TransformNest = Input { },
				ReferenceSize = Input { },
				Input = Input {
					SourceOp = "Merge1_2_1",
					Source = "Output",
				},
				EffectMask = Input { }
			},
			ViewInfo = OperatorInfo { Pos = { -220, 148.5 } },
		},
		Instance_Scale1_1_1 = Scale {
			SourceOp = "Instance_Scale1_2_1",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_1_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 346.5 } },
		},
		Saver1_2_1_2 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/4C.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_2_1_2",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 709.5 } },
		},
		Text1 = TextPlus {
			CtrlWZoom = false,
			Inputs = {
				HorizontalJustificationNew = Input { Value = 3, },
				VerticalJustificationNew = Input { Value = 3, },
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.48581986497545, 0.5 }, },
				Size = Input { Value = 0.01, },
				Font = Input { Value = "Open Sans", },
				StyledText = Input { Value = "D", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { -220, -280.5 } },
		},
		Merge2 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Loader1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Background1",
					Source = "Output",
				},
				PerformDepthMerge = Input { Value = 0, },
				EffectMask = Input {
					SourceOp = "Polygon2",
					Source = "Mask",
				}
			},
			ViewInfo = OperatorInfo { Pos = { -55, -16.5 } },
		},
		Merge3_2_1_2_1_8 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3_8",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.348452853538338 }, },
				Size = Input { Value = 0.864555848724714, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -220, 1831.5 } },
		},
		ColorCorrector1 = ColorCorrector {
			Inputs = {
				WheelSaturation1 = Input { Value = 0, },
				MasterRGBGain = Input { Value = 0, },
				ColorRanges = Input {
					Value = ColorCurves {
						Curves = {
							{
								Points = {
									{ 0, 1 },
									{ 0.4, 0.2 },
									{ 0.6, 0 },
									{ 1, 0 }
								}
							},
							{
								Points = {
									{ 0, 0 },
									{ 0.4, 0 },
									{ 0.6, 0.2 },
									{ 1, 1 }
								}
							}
						}
					},
				},
				HistogramIgnoreTransparent = Input { Value = 1, },
				Input = Input {
					SourceOp = "Instance_Transform4_10",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -605, 1501.5 } },
		},
		Saver1_5_6 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/8H.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_4_6",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1402.5 } },
		},
		Instance_Scale1_2_1_1 = Scale {
			Inputs = {
				XSize = Input { Value = 0.3333, },
				HiQOnly = Input { Value = 0, },
				PixelAspect = Input { Value = { 1, 1 }, },
				Input = Input {
					SourceOp = "Instance_Crop1_2_1_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 544.5 } },
		},
		Merge3_2_2_10 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2_10",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_2",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.336847437677603 }, },
				Size = Input { Value = 0.949970674486804, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 0, 2227.5 } },
		},
		Instance_Scale1_1_1_4 = Scale {
			SourceOp = "Instance_Scale1_2_1_4",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_1_1_4",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1006.5 } },
		},
		Instance_Scale1_3_1_7 = Scale {
			SourceOp = "Instance_Scale1_2_1_7",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_3_1_7",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1765.5 } },
		},
		Merge3_2 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_2",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.336847437677603 }, },
				Size = Input { Value = 0.949970674486804, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 0, 1567.5 } },
		},
		Instance_Crop1_1_1_11 = Crop {
			SourceOp = "Instance_Crop1_2_1_11",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_2_1_11",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 2326.5 } },
		},
		ColorCorrector1_2_1 = ColorCorrector {
			Inputs = {
				WheelSaturation1 = Input { Value = 0, },
				MasterRGBGain = Input { Value = 0, },
				ColorRanges = Input {
					Value = ColorCurves {
						Curves = {
							{
								Points = {
									{ 0, 1 },
									{ 0.4, 0.2 },
									{ 0.6, 0 },
									{ 1, 0 }
								}
							},
							{
								Points = {
									{ 0, 0 },
									{ 0.4, 0 },
									{ 0.6, 0.2 },
									{ 1, 1 }
								}
							}
						}
					},
				},
				HistogramIgnoreTransparent = Input { Value = 1, },
				Input = Input {
					SourceOp = "Instance_Transform4_4",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -605, 511.5 } },
		},
		Merge3_2_1_1_1_5 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3_5",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_1",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.34458438158476 }, },
				Size = Input { Value = 0.961301671064204, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -110, 1204.5 } },
		},
		Instance_Scale1_4_6 = Scale {
			SourceOp = "Instance_Scale1_2_1_6",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_4_6",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1402.5 } },
		},
		Background1_1 = Background {
			Inputs = {
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 693, },
				Height = Input { Value = 175, },
				EffectMask = Input {
					SourceOp = "LumaKeyer1",
					Source = "Output",
				}
			},
			ViewInfo = OperatorInfo { Pos = { -165, 82.5 } },
		},
		Instance_Scale1_3_1_8 = Scale {
			SourceOp = "Instance_Scale1_2_1_8",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_3_1_8",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1930.5 } },
		},
		Instance_Crop1_2_1_9 = Crop {
			Inputs = {
				XOffset = Input { Value = 56, },
				YOffset = Input { Value = 60, },
				XSize = Input { Value = 108, },
				YSize = Input { Value = 180, },
				KeepCentered = Input { Value = 1, },
				Input = Input {
					SourceOp = "Merge3_2_1_1_1_9",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 220, 2029.5 } },
		},
		Instance_Crop1 = Crop {
			SourceOp = "Crop1",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1567.5 } },
		},
		Merge5 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Transform2",
					Source = "Output",
				},
				Center = Input { Value = { 0.580712991075326, 0.4400456497493 }, },
				ApplyMode = Input { Value = FuID { "Multiply" }, },
				PerformDepthMerge = Input { Value = 0, },
				EffectMask = Input {
					SourceOp = "Polygon4",
					Source = "Mask",
				}
			},
			ViewInfo = OperatorInfo { Pos = { -385, 214.5 } },
		},
		Instance_Crop1_2_1_8 = Crop {
			Inputs = {
				XOffset = Input { Value = 56, },
				YOffset = Input { Value = 60, },
				XSize = Input { Value = 108, },
				YSize = Input { Value = 180, },
				KeepCentered = Input { Value = 1, },
				Input = Input {
					SourceOp = "Merge3_2_1_1_1_8",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1864.5 } },
		},
		Saver1_2_1_5 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/7C.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_2_1_5",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1204.5 } },
		},
		Merge4_1_3_5 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "ColorCorrector1_2_5",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 1171.5 } },
		},
		Instance_Scale1_2_1_5 = Scale {
			Inputs = {
				XSize = Input { Value = 0.3333, },
				HiQOnly = Input { Value = 0, },
				PixelAspect = Input { Value = { 1, 1 }, },
				Input = Input {
					SourceOp = "Instance_Crop1_2_1_5",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1204.5 } },
		},
		Merge3_2_1_1_1_3 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3_3",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_1",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.34458438158476 }, },
				Size = Input { Value = 0.961301671064204, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -110, 874.5 } },
		},
		Saver1_3_1_1 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/3S.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_1_1_1",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 511.5 } },
		},
		Instance_Transform4_9 = Transform {
			SourceOp = "Transform4",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				TransformNest = Input { },
				ReferenceSize = Input { },
				Input = Input {
					SourceOp = "Text1_1_1_6",
					Source = "Output",
				},
				EffectMask = Input { }
			},
			ViewInfo = OperatorInfo { Pos = { -715, 1336.5 } },
		},
		Instance_Crop1_3_1 = Crop {
			SourceOp = "Instance_Crop1_2_1",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_3",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 445.5 } },
		},
		Merge3_2_1_2_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.348452853538338 }, },
				Size = Input { Value = 0.864555848724714, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -220, 346.5 } },
		},
		Polygon2 = PolylineMask {
			DrawMode = "InsertAndModify",
			DrawMode2 = "InsertAndModify",
			Inputs = {
				MaskWidth = Input { Value = 1920, },
				MaskHeight = Input { Value = 1080, },
				PixelAspect = Input { Value = { 1, 1 }, },
				ClippingMode = Input { Value = FuID { "None" }, },
				Polyline = Input {
					SourceOp = "Polygon2Polyline",
					Source = "Value",
				},
				Polyline2 = Input {
					Value = Polyline {
					},
					Disabled = true,
				},
				EffectMask = Input {
					SourceOp = "Polygon1",
					Source = "Mask",
				}
			},
			ViewInfo = OperatorInfo { Pos = { -165, -16.5 } },
		},
		Merge3_2_1_2_1_5 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3_5",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.348452853538338 }, },
				Size = Input { Value = 0.864555848724714, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -220, 1171.5 } },
		},
		Merge3_2_2_4 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2_4",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_2",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.336847437677603 }, },
				Size = Input { Value = 0.949970674486804, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 0, 1072.5 } },
		},
		Merge3_2_2_2 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2_2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_2",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.336847437677603 }, },
				Size = Input { Value = 0.949970674486804, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 0, 742.5 } },
		},
		Instance_Scale1_3_1_4 = Scale {
			SourceOp = "Instance_Scale1_2_1_4",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_3_1_4",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1105.5 } },
		},
		ColorCorrector1_2_4 = ColorCorrector {
			Inputs = {
				WheelSaturation1 = Input { Value = 0, },
				MasterRGBGain = Input { Value = 0, },
				ColorRanges = Input {
					Value = ColorCurves {
						Curves = {
							{
								Points = {
									{ 0, 1 },
									{ 0.4, 0.2 },
									{ 0.6, 0 },
									{ 1, 0 }
								}
							},
							{
								Points = {
									{ 0, 0 },
									{ 0.4, 0 },
									{ 0.6, 0.2 },
									{ 1, 1 }
								}
							}
						}
					},
				},
				HistogramIgnoreTransparent = Input { Value = 1, },
				Input = Input {
					SourceOp = "Instance_Transform4_7",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -605, 1006.5 } },
		},
		Saver1_3_1_10 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/KS.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_1_1_10",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 2161.5 } },
		},
		Merge3_2_1_2_1_2 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3_2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.348452853538338 }, },
				Size = Input { Value = 0.864555848724714, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -220, 676.5 } },
		},
		Merge3_2_1_3_9 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2_9",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_3",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.354255561468705 }, },
				Size = Input { Value = 0.883932231992637, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 110, 2095.5 } },
		},
		Instance_Crop1_1_1 = Crop {
			SourceOp = "Instance_Crop1_2_1",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_2_1",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 346.5 } },
		},
		Crop1 = Crop {
			Inputs = {
				XOffset = Input { Value = 56, },
				YOffset = Input { Value = 60, },
				XSize = Input { Value = 108, },
				YSize = Input { Value = 180, },
				KeepCentered = Input { Value = 1, },
				Input = Input {
					SourceOp = "Merge5",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 220, 214.5 } },
		},
		Saver1_3_1_7 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/TS.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_1_1_7",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1666.5 } },
		},
		Instance_Scale1_2_1_6 = Scale {
			Inputs = {
				XSize = Input { Value = 0.3333, },
				HiQOnly = Input { Value = 0, },
				PixelAspect = Input { Value = { 1, 1 }, },
				Input = Input {
					SourceOp = "Instance_Crop1_2_1_6",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1369.5 } },
		},
		Rectangle4 = RectangleMask {
			Inputs = {
				Filter = Input { Value = FuID { "Fast Gaussian" }, },
				MaskWidth = Input { Value = 1920, },
				MaskHeight = Input { Value = 1080, },
				PixelAspect = Input { Value = { 1, 1 }, },
				ClippingMode = Input { Value = FuID { "None" }, },
				Center = Input { Value = { 0.5, 0.341715976331361 }, },
				Height = Input { Value = 0.476353928299008, },
			},
			ViewInfo = OperatorInfo { Pos = { -825, 1798.5 } },
		},
		Instance_Crop1_1_1_6 = Crop {
			SourceOp = "Instance_Crop1_2_1_6",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_2_1_6",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1336.5 } },
		},
		Instance_Scale1_1_1_10 = Scale {
			SourceOp = "Instance_Scale1_2_1_10",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_1_1_10",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 2161.5 } },
		},
		Ellipse2 = EllipseMask {
			Inputs = {
				Filter = Input { Value = FuID { "Fast Gaussian" }, },
				MaskWidth = Input { Value = 1920, },
				MaskHeight = Input { Value = 1080, },
				PixelAspect = Input { Value = { 1, 1 }, },
				ClippingMode = Input { Value = FuID { "None" }, },
				Center = Input { Value = { -0.317629179331307, 1.37323943661972 }, },
			},
			ViewInfo = OperatorInfo { Pos = { -440, -214.5 } },
		},
		Merge3_2_2_7 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2_7",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_2",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.336847437677603 }, },
				Size = Input { Value = 0.949970674486804, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 0, 1732.5 } },
		},
		Merge4_1_1_2_7 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_11",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 1732.5 } },
		},
		Instance_Transform3 = Transform {
			SourceOp = "Transform3",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				TransformNest = Input { },
				ReferenceSize = Input { },
				Input = Input {
					SourceOp = "Merge10",
					Source = "Output",
				},
				EffectMask = Input { }
			},
			ViewInfo = OperatorInfo { Pos = { 0, -445.5 } },
		},
		Merge4_1_1_2_4 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_7",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 1072.5 } },
		},
		Instance_Scale1_3_1_11 = Scale {
			SourceOp = "Instance_Scale1_2_1_11",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_3_1_11",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 2425.5 } },
		},
		Saver1_3_1_5 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/7S.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_1_1_5",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1171.5 } },
		},
		Text1_1_1_2 = TextPlus {
			Inputs = {
				HorizontalJustificationNew = Input { Value = 3, },
				VerticalJustificationNew = Input { Value = 3, },
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				Center = Input { Value = { 0.5, 0.545083011716293 }, },
				Font = Input { Value = "DejaVu Sans", },
				StyledText = Input { Value = "4", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Alignment = Input { Value = 1, },
				HorizontalJustification = Input { Value = 1, },
				Red1 = Input { Value = 0.778792858123779, },
				Green1 = Input { Value = 0.0274509191513062, },
				Blue1 = Input { Value = 0.0961014628410339, },
			},
			ViewInfo = OperatorInfo { Pos = { -825, 676.5 } },
		},
		Merge3_2_1_2_1_7 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3_7",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.348452853538338 }, },
				Size = Input { Value = 0.864555848724714, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -220, 1666.5 } },
		},
		Background4_1_1_1 = Background {
			Inputs = {
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 70, },
				Height = Input { Value = 70, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				TopLeftRed = Input { Value = 1, },
				TopLeftGreen = Input { Value = 1, },
				TopLeftBlue = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { -275, -412.5 } },
		},
		Saver1_2_1_4 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/6C.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_2_1_4",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1039.5 } },
		},
		Merge4_1_1_2 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Transform4",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 412.5 } },
		},
		Instance_Transform4_13 = Transform {
			SourceOp = "Transform4",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				TransformNest = Input { },
				ReferenceSize = Input { },
				Input = Input {
					SourceOp = "Text1_1_1_9",
					Source = "Output",
				},
				EffectMask = Input { }
			},
			ViewInfo = OperatorInfo { Pos = { -715, 1996.5 } },
		},
		ColorCorrector1_2_6 = ColorCorrector {
			Inputs = {
				WheelSaturation1 = Input { Value = 0, },
				MasterRGBGain = Input { Value = 0, },
				ColorRanges = Input {
					Value = ColorCurves {
						Curves = {
							{
								Points = {
									{ 0, 1 },
									{ 0.4, 0.2 },
									{ 0.6, 0 },
									{ 1, 0 }
								}
							},
							{
								Points = {
									{ 0, 0 },
									{ 0.4, 0 },
									{ 0.6, 0.2 },
									{ 1, 1 }
								}
							}
						}
					},
				},
				HistogramIgnoreTransparent = Input { Value = 1, },
				Input = Input {
					SourceOp = "Instance_Transform4_9",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -605, 1336.5 } },
		},
		Instance_Scale1_4_2 = Scale {
			SourceOp = "Instance_Scale1_2_1_2",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_4_2",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 742.5 } },
		},
		Merge4_1_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_10",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 1567.5 } },
		},
		Instance_Transform4_11 = Transform {
			SourceOp = "Transform4",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				TransformNest = Input { },
				ReferenceSize = Input { },
				Input = Input {
					SourceOp = "Text1_1_1_7",
					Source = "Output",
				},
				EffectMask = Input { }
			},
			ViewInfo = OperatorInfo { Pos = { -715, 1666.5 } },
		},
		Polygon3Polyline = BezierSpline {
			SplineColor = { Red = 173, Green = 255, Blue = 47 },
			NameSet = true,
			KeyFrames = {
				[0] = { 0, Flags = { Linear = true, LockedY = true }, Value = Polyline {
						Closed = true,
						Points = {
							{ Linear = true, X = -0.192546581907302, Y = -0.291347935541498, LX = -0.00931677034059173, LY = 0.00885092706946111, RX = 0.127674256761869, RY = 0.000505814949671427 },
							{ Linear = true, X = 0.190476188378304, Y = -0.289830490692484, LX = -0.127674256761869, LY = -0.000505814949671427, RX = 0.011387166275988, RY = 0.00834511211978969 },
							{ Linear = true, X = 0.224637687206268, Y = -0.264795154333115, LX = -0.011387166275988, LY = -0.00834511211978969, RX = 0.00345065360895265, RY = 0.0126454257488733 },
							{ Linear = true, X = 0.234989643096924, Y = -0.226858884096146, LX = -0.00345065360895265, LY = -0.0126454257488733, RX = 0, RY = 0.153768338198968 },
							{ Linear = true, X = 0.234989643096924, Y = 0.234446123242378, LX = 0, LY = -0.153768338198968, RX = -0.0062111784788228, RY = 0.0151745092479882 },
							{ Linear = true, X = 0.216356113553047, Y = 0.279969662427902, LX = 0.0062111784788228, LY = -0.0151745092479882, RX = -0.0151828867122993, RY = 0.00354071444613679 },
							{ Linear = true, X = 0.17080745100975, Y = 0.290591806173325, LX = 0.0151828867122993, LY = -0.00354071444613679, RX = -0.119392683807943, RY = -0.000505817029954928 },
							{ Linear = true, X = -0.187370598316193, Y = 0.28907436132431, LX = 0.119392683807943, LY = 0.000505817029954928, RX = -0.0124223609477426, RY = -0.0096105230716846 },
							{ Linear = true, X = -0.224637687206268, Y = 0.260242789983749, LX = 0.0124223609477426, LY = 0.0096105230716846, RX = -0.00276052248403893, RY = -0.00859888649433023 },
							{ Linear = true, X = -0.232919260859489, Y = 0.234446123242378, LX = 0.00276052248403893, LY = 0.00859888649433023, RX = -0.00138026018279269, RY = -0.152756699654389 },
							{ Linear = true, X = -0.237060040235519, Y = -0.223823979496956, LX = 0.00138026018279269, LY = 0.152756699654389, RX = 0.00552104860852716, RY = -0.013657054886953 },
							{ Linear = true, X = -0.220496892929077, Y = -0.264795154333115, LX = -0.00552104860852716, LY = 0.013657054886953, RX = 0.00931677034059173, RY = -0.00885092706946111 }
						}
					} }
			}
		},
		Background4 = Background {
			Inputs = {
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 70, },
				Height = Input { Value = 15, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				TopLeftRed = Input { Value = 0.685, },
				EffectMask = Input {
					SourceOp = "Ellipse1",
					Source = "Mask",
				}
			},
			ViewInfo = OperatorInfo { Pos = { -330, -247.5 } },
		},
		Saver1_1 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/REV.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Scale1",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 214.5 } },
		},
		Instance_Scale1_4_7 = Scale {
			SourceOp = "Instance_Scale1_2_1_7",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_4_7",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1732.5 } },
		},
		Merge3_2_1_1_1_9 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3_9",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_1",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.34458438158476 }, },
				Size = Input { Value = 0.961301671064204, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -110, 2029.5 } },
		},
		Merge3_2_1_2_1_11 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3_11",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.348452853538338 }, },
				Size = Input { Value = 0.864555848724714, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -220, 2326.5 } },
		},
		Saver1_4_1_6 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/8D.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_3_1_6",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1435.5 } },
		},
		Instance_Crop1_3_1_3 = Crop {
			SourceOp = "Instance_Crop1_2_1_3",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_3_3",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 940.5 } },
		},
		Saver1_3_1_8 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/JS.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_1_1_8",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1831.5 } },
		},
		Instance_Crop1_1_1_5 = Crop {
			SourceOp = "Instance_Crop1_2_1_5",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_2_1_5",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1171.5 } },
		},
		Saver1_3_1 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/2S.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_1_1",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 346.5 } },
		},
		Instance_Scale1_3_1_2 = Scale {
			SourceOp = "Instance_Scale1_2_1_2",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_3_1_2",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 775.5 } },
		},
		Instance_Scale1_1_1_5 = Scale {
			SourceOp = "Instance_Scale1_2_1_5",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_1_1_5",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1171.5 } },
		},
		Saver1_5_8 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/JH.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_4_8",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1897.5 } },
		},
		Merge3_2_2_11 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2_11",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_2",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.336847437677603 }, },
				Size = Input { Value = 0.949970674486804, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 0, 2392.5 } },
		},
		Saver1_5 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/2H.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_4",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 412.5 } },
		},
		Instance_Crop1_3_1_11 = Crop {
			SourceOp = "Instance_Crop1_2_1_11",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_3_11",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 2425.5 } },
		},
		Instance_Scale1_1_1_3 = Scale {
			SourceOp = "Instance_Scale1_2_1_3",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_1_1_3",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 841.5 } },
		},
		Merge3_2_1_3_5 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2_5",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_3",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.354255561468705 }, },
				Size = Input { Value = 0.883932231992637, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 110, 1270.5 } },
		},
		Polygon2Polyline = BezierSpline {
			SplineColor = { Red = 96, Green = 255, Blue = 47 },
			NameSet = true,
			KeyFrames = {
				[0] = { 0, Flags = { Linear = true, LockedY = true }, Value = Polyline {
						Closed = true,
						Points = {
							{ Linear = true, X = -0.305738180875778, Y = -0.151434645056725, LX = 0.136680607994397, LY = 0.00921006004015605, RX = 0.00219166698648672, RY = 0.113708820757484 },
							{ Linear = true, X = -0.299163192510605, Y = 0.189691811800003, LX = -0.00219166698648672, LY = -0.113708820757484, RX = 0.0127515483303929, RY = 0.00141693414672232 },
							{ Linear = true, X = -0.260908544063568, Y = 0.193942621350288, LX = -0.0127515483303929, LY = -0.00141693414672232, RX = 0.00159394186458447, RY = -0.106624161066462 },
							{ Linear = true, X = -0.25612673163414, Y = -0.125929862260818, LX = -0.00159394186458447, LY = 0.106624161066462, RX = 0.0458258661135518, RY = 0.00212539864946163 },
							{ Linear = true, X = -0.118649132549763, Y = -0.119553662836552, LX = -0.0458258661135518, LY = -0.00212539864946163, RX = 0.00179318564569695, RY = 0.112291886903718 },
							{ Linear = true, X = -0.113269574940205, Y = 0.217321991920471, LX = -0.00179318564569695, LY = -0.112291886903718, RX = 0.00976290083378049, RY = 0.000708468852210357 },
							{ Linear = true, X = -0.0839808724388631, Y = 0.219447398477102, LX = -0.00976290083378049, LY = -0.000708468852210357, RX = 0.00019924256681184, RY = -0.112291888194307 },
							{ Linear = true, X = -0.0833831447384276, Y = -0.117428266105819, LX = -0.00019924256681184, LY = 0.112291888194307, RX = 0.0484160190827819, RY = -0.00141693383529175 },
							{ Linear = true, X = 0.0618649125099182, Y = -0.121679067611694, LX = -0.0484160190827819, LY = 0.00141693383529175, RX = 0.00199242904381488, RY = 0.112291888991358 },
							{ Linear = true, X = 0.0678422003984451, Y = 0.215196594595909, LX = -0.00199242904381488, LY = -0.112291888991358, RX = 0.00777047195325786, RY = 0.00106270084493428 },
							{ Linear = true, X = 0.0911536142230034, Y = 0.218384698033333, LX = -0.00777047195325786, LY = -0.00106270084493428, RX = 0.00438334397388233, RY = -0.114063053790069 },
							{ Linear = true, X = 0.104303643107414, Y = -0.123804464936256, LX = -0.00438334397388233, LY = 0.114063053790069, RX = -0.136680607994397, RY = -0.00921006004015605 }
						}
					} }
			}
		},
		Instance_Scale1_4_9 = Scale {
			SourceOp = "Instance_Scale1_2_1_9",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_4_9",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 2062.5 } },
		},
		Merge3_2_2_8 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2_8",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_2",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.336847437677603 }, },
				Size = Input { Value = 0.949970674486804, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 0, 1897.5 } },
		},
		Ellipse3_1_1 = EllipseMask {
			Inputs = {
				Filter = Input { Value = FuID { "Fast Gaussian" }, },
				MaskWidth = Input { Value = 1920, },
				MaskHeight = Input { Value = 1080, },
				PixelAspect = Input { Value = { 1, 1 }, },
				ClippingMode = Input { Value = FuID { "None" }, },
				Width = Input { Value = 0.836779245530853, },
				Height = Input { Value = 0.836779245530853, },
			},
			ViewInfo = OperatorInfo { Pos = { -275, -346.5 } },
		},
		Saver1_5_4 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/6H.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_4_4",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1072.5 } },
		},
		Saver1_5_11 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/AH.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_4_11",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 2392.5 } },
		},
		Ellipse3_1 = EllipseMask {
			Inputs = {
				Filter = Input { Value = FuID { "Fast Gaussian" }, },
				MaskWidth = Input { Value = 1920, },
				MaskHeight = Input { Value = 1080, },
				PixelAspect = Input { Value = { 1, 1 }, },
				ClippingMode = Input { Value = FuID { "None" }, },
				Width = Input { Value = 0.929509274271438, },
				Height = Input { Value = 0.929509274271438, },
			},
			ViewInfo = OperatorInfo { Pos = { -440, -346.5 } },
		},
		Merge1_2_1_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background1_1_2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Background1_1",
					Source = "Output",
				},
				Center = Input { Value = { -0.465493388515801, 0.231103286384977 }, },
				PerformDepthMerge = Input { Value = 0, },
				EffectMask = Input {
					SourceOp = "Rectangle2",
					Source = "Mask",
				}
			},
			ViewInfo = OperatorInfo { Pos = { -110, 115.5 } },
		},
		Saver1_5_3 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/5H.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_4_3",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 907.5 } },
		},
		Instance_Crop1_1_1_7 = Crop {
			SourceOp = "Instance_Crop1_2_1_7",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_2_1_7",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1666.5 } },
		},
		Instance_Transform4_10 = Transform {
			SourceOp = "Transform4",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				TransformNest = Input { },
				ReferenceSize = Input { },
				Input = Input {
					SourceOp = "Text1_1",
					Source = "Output",
				},
				EffectMask = Input { }
			},
			ViewInfo = OperatorInfo { Pos = { -715, 1501.5 } },
		},
		Merge4_1_3_10 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "ColorCorrector1_2_10",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 2161.5 } },
		},
		Saver1_3_1_2 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/4S.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_1_1_2",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 676.5 } },
		},
		Saver1_3_1_4 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/6S.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_1_1_4",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1006.5 } },
		},
		Merge11_1 = Merge {
			CtrlWZoom = false,
			Inputs = {
				Background = Input {
					SourceOp = "Background3_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader5",
					Source = "Output",
				},
				Size = Input { Value = 0.1369917522689, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 110, -544.5 } },
		},
		Merge4_1_3_2 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "ColorCorrector1_2_2",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 676.5 } },
		},
		Instance_Crop1_2_1_10 = Crop {
			Inputs = {
				XOffset = Input { Value = 56, },
				YOffset = Input { Value = 60, },
				XSize = Input { Value = 108, },
				YSize = Input { Value = 180, },
				KeepCentered = Input { Value = 1, },
				Input = Input {
					SourceOp = "Merge3_2_1_1_1_10",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 220, 2194.5 } },
		},
		Instance_Crop1_2_1_6 = Crop {
			Inputs = {
				XOffset = Input { Value = 56, },
				YOffset = Input { Value = 60, },
				XSize = Input { Value = 108, },
				YSize = Input { Value = 180, },
				KeepCentered = Input { Value = 1, },
				Input = Input {
					SourceOp = "Merge3_2_1_1_1_6",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1369.5 } },
		},
		Instance_Scale1_1_1_2 = Scale {
			SourceOp = "Instance_Scale1_2_1_2",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_1_1_2",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 676.5 } },
		},
		Instance_Scale1_4_3 = Scale {
			SourceOp = "Instance_Scale1_2_1_3",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_4_3",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 907.5 } },
		},
		Saver1_4_1_4 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/6D.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_3_1_4",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1105.5 } },
		},
		Merge1_2 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background1_1_2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Background1_1_1",
					Source = "Output",
				},
				Center = Input { Value = { 1.80175438596491, 0.231103286384977 }, },
				PerformDepthMerge = Input { Value = 0, },
				EffectMask = Input {
					SourceOp = "Rectangle2",
					Source = "Mask",
				}
			},
			ViewInfo = OperatorInfo { Pos = { 110, 115.5 } },
		},
		Polygon1 = PolylineMask {
			DrawMode = "InsertAndModify",
			DrawMode2 = "InsertAndModify",
			Inputs = {
				Invert = Input { Value = 1, },
				MaskWidth = Input { Value = 1920, },
				MaskHeight = Input { Value = 1080, },
				PixelAspect = Input { Value = { 1, 1 }, },
				ClippingMode = Input { Value = FuID { "None" }, },
				Polyline = Input {
					SourceOp = "Polygon1Polyline",
					Source = "Value",
				},
				Polyline2 = Input {
					Value = Polyline {
					},
					Disabled = true,
				},
			},
			ViewInfo = OperatorInfo { Pos = { -275, -16.5 } },
		},
		Merge3_2_1_1_1_4 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3_4",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_1",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.34458438158476 }, },
				Size = Input { Value = 0.961301671064204, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -110, 1039.5 } },
		},
		Instance_Scale1_2_1_11 = Scale {
			Inputs = {
				XSize = Input { Value = 0.3333, },
				HiQOnly = Input { Value = 0, },
				PixelAspect = Input { Value = { 1, 1 }, },
				Input = Input {
					SourceOp = "Instance_Crop1_2_1_11",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 2359.5 } },
		},
		Instance_Transform4_14 = Transform {
			SourceOp = "Transform4",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				TransformNest = Input { },
				ReferenceSize = Input { },
				Input = Input {
					SourceOp = "Text1_1_1_10",
					Source = "Output",
				},
				EffectMask = Input { }
			},
			ViewInfo = OperatorInfo { Pos = { -715, 2161.5 } },
		},
		Polygon5Polyline = BezierSpline {
			SplineColor = { Red = 173, Green = 255, Blue = 47 },
			NameSet = true,
			KeyFrames = {
				[0] = { 0, Flags = { Linear = true, LockedY = true }, Value = Polyline {
						Closed = true,
						Points = {
							{ Linear = true, X = -0.259541988372803, Y = -0.0839694663882256, LX = -0.0210114506288946, LY = -0.046207841248761, RX = 0.174300251267945, RY = 0.00127226468791791 },
							{ Linear = true, X = 0.263358765431033, Y = -0.0801526723244718, LX = -0.174300251267945, LY = -0.00127226468791791, RX = -0.00381678964648842, RY = -0.0865139908538823 },
							{ Linear = true, X = 0.251908396491568, Y = -0.339694644886119, LX = 0.00381678964648842, LY = 0.0865139908538823, RX = -0.160305342677289, RY = 0.00508905314003845 },
							{ Linear = true, X = -0.229007631540298, Y = -0.324427485466003, LX = 0.160305342677289, LY = -0.00508905314003845, RX = -0.0311895695730627, RY = 0.033944831777165 },
							{ Linear = true, X = -0.322576340259486, Y = -0.222592990134509, LX = 0.0311895695730627, LY = -0.033944831777165, RX = 0.0210114506288946, RY = 0.046207841248761 }
						}
					} }
			}
		},
		Saver1_4_1_2 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/4D.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_3_1_2",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 775.5 } },
		},
		Instance_Scale1_2_1_4 = Scale {
			Inputs = {
				XSize = Input { Value = 0.3333, },
				HiQOnly = Input { Value = 0, },
				PixelAspect = Input { Value = { 1, 1 }, },
				Input = Input {
					SourceOp = "Instance_Crop1_2_1_4",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1039.5 } },
		},
		Instance_Scale1_3 = Scale {
			SourceOp = "Scale1",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_3",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1600.5 } },
		},
		Saver1_5_7 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/TH.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_4_7",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1732.5 } },
		},
		Instance_Transform4_6 = Transform {
			SourceOp = "Transform4",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				TransformNest = Input { },
				ReferenceSize = Input { },
				Input = Input {
					SourceOp = "Text1_1_1_3",
					Source = "Output",
				},
				EffectMask = Input { }
			},
			ViewInfo = OperatorInfo { Pos = { -715, 841.5 } },
		},
		Rectangle3 = RectangleMask {
			Inputs = {
				Filter = Input { Value = FuID { "Fast Gaussian" }, },
				MaskWidth = Input { Value = 1920, },
				MaskHeight = Input { Value = 1080, },
				PixelAspect = Input { Value = { 1, 1 }, },
				ClippingMode = Input { Value = FuID { "None" }, },
				Center = Input { Value = { -0.021680216802168, 0.5 }, },
				Height = Input { Value = 1.16124661246612, },
			},
			ViewInfo = OperatorInfo { Pos = { -935, 181.5 } },
		},
		Saver1_2_1_6 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/8C.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_2_1_6",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1369.5 } },
		},
		Saver1_2 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/9C.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_2",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1534.5 } },
		},
		Instance_Crop1_4_11 = Crop {
			SourceOp = "Instance_Crop1_2_1_11",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_2_11",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 2392.5 } },
		},
		ColorCorrector1_2_10 = ColorCorrector {
			Inputs = {
				WheelSaturation1 = Input { Value = 0, },
				MasterRGBGain = Input { Value = 0, },
				ColorRanges = Input {
					Value = ColorCurves {
						Curves = {
							{
								Points = {
									{ 0, 1 },
									{ 0.4, 0.2 },
									{ 0.6, 0 },
									{ 1, 0 }
								}
							},
							{
								Points = {
									{ 0, 0 },
									{ 0.4, 0 },
									{ 0.6, 0.2 },
									{ 1, 1 }
								}
							}
						}
					},
				},
				HistogramIgnoreTransparent = Input { Value = 1, },
				Input = Input {
					SourceOp = "Instance_Transform4_14",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -605, 2161.5 } },
		},
		Saver1_4_1_1 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/3D.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_3_1_1",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 610.5 } },
		},
		ColorCorrector1_2_11 = ColorCorrector {
			Inputs = {
				WheelSaturation1 = Input { Value = 0, },
				MasterRGBGain = Input { Value = 0, },
				ColorRanges = Input {
					Value = ColorCurves {
						Curves = {
							{
								Points = {
									{ 0, 1 },
									{ 0.4, 0.2 },
									{ 0.6, 0 },
									{ 1, 0 }
								}
							},
							{
								Points = {
									{ 0, 0 },
									{ 0.4, 0 },
									{ 0.6, 0.2 },
									{ 1, 1 }
								}
							}
						}
					},
				},
				HistogramIgnoreTransparent = Input { Value = 1, },
				Input = Input {
					SourceOp = "Instance_Transform4_15",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -605, 2326.5 } },
		},
		Instance_Scale1_3_1_10 = Scale {
			SourceOp = "Instance_Scale1_2_1_10",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_3_1_10",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 2260.5 } },
		},
		Merge3_2_1_2_1_9 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3_9",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.348452853538338 }, },
				Size = Input { Value = 0.864555848724714, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -220, 1996.5 } },
		},
		Ellipse3 = EllipseMask {
			Inputs = {
				Filter = Input { Value = FuID { "Fast Gaussian" }, },
				MaskWidth = Input { Value = 1920, },
				MaskHeight = Input { Value = 1080, },
				PixelAspect = Input { Value = { 1, 1 }, },
				ClippingMode = Input { Value = FuID { "None" }, },
				Width = Input { Value = 0.972366918069384, },
				Height = Input { Value = 0.972366918069384, },
			},
			ViewInfo = OperatorInfo { Pos = { -660, -379.5 } },
		},
		Merge3_2_1_2_1_3 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3_3",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.348452853538338 }, },
				Size = Input { Value = 0.864555848724714, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -220, 841.5 } },
		},
		Saver1_5_1 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/3H.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_4_1",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 577.5 } },
		},
		Saver1_3_1_9 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/DS.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_1_1_9",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1996.5 } },
		},
		Instance_Scale1_3_1_9 = Scale {
			SourceOp = "Instance_Scale1_2_1_9",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_3_1_9",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 2095.5 } },
		},
		Merge1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background1_1_2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Background1_1_1",
					Source = "Output",
				},
				Center = Input { Value = { 3.00175438596491, 0.231103286384977 }, },
				PerformDepthMerge = Input { Value = 0, },
				EffectMask = Input {
					SourceOp = "Rectangle2",
					Source = "Mask",
				}
			},
			ViewInfo = OperatorInfo { Pos = { 0, 115.5 } },
		},
		Saver1_4 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/9D.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_3",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1600.5 } },
		},
		Background2 = Background {
			Inputs = {
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 220, },
				Height = Input { Value = 300, },
				TopLeftRed = Input { Value = 1, },
				TopLeftGreen = Input { Value = 1, },
				TopLeftBlue = Input { Value = 1, },
				EffectMask = Input {
					SourceOp = "Rectangle1",
					Source = "Mask",
				}
			},
			ViewInfo = OperatorInfo { Pos = { -495, 115.5 } },
		},
		Text1_1_1_5 = TextPlus {
			Inputs = {
				HorizontalJustificationNew = Input { Value = 3, },
				VerticalJustificationNew = Input { Value = 3, },
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				Center = Input { Value = { 0.5, 0.545083011716293 }, },
				Font = Input { Value = "DejaVu Sans", },
				StyledText = Input { Value = "7", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Alignment = Input { Value = 1, },
				HorizontalJustification = Input { Value = 1, },
				Red1 = Input { Value = 0.778792858123779, },
				Green1 = Input { Value = 0.0274509191513062, },
				Blue1 = Input { Value = 0.0961014628410339, },
			},
			ViewInfo = OperatorInfo { Pos = { -825, 1171.5 } },
		},
		Instance_Crop1_4_7 = Crop {
			SourceOp = "Instance_Crop1_2_1_7",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_2_7",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1732.5 } },
		},
		Saver1_3_1_6 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/8S.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_1_1_6",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1336.5 } },
		},
		Instance_Crop1_2 = Crop {
			SourceOp = "Crop1",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_1",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1534.5 } },
		},
		Saver1_3_1_3 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/5S.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_1_1_3",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 841.5 } },
		},
		Instance_Crop1_2_1_4 = Crop {
			Inputs = {
				XOffset = Input { Value = 56, },
				YOffset = Input { Value = 60, },
				XSize = Input { Value = 108, },
				YSize = Input { Value = 180, },
				KeepCentered = Input { Value = 1, },
				Input = Input {
					SourceOp = "Merge3_2_1_1_1_4",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1039.5 } },
		},
		Instance_Crop1_3_1_4 = Crop {
			SourceOp = "Instance_Crop1_2_1_4",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_3_4",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1105.5 } },
		},
		Merge3 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background3",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader5",
					Source = "Output",
				},
				Size = Input { Value = 0.1020625, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -275, -544.5 } },
		},
		Saver1_4_1_7 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/TD.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_3_1_7",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1765.5 } },
		},
		Crop2 = Crop {
			Inputs = {
				XOffset = Input { Value = 495, },
				YOffset = Input { Value = 175, },
				XSize = Input { Value = 290, },
				YSize = Input { Value = 290, },
				KeepCentered = Input { Value = 1, },
				Input = Input {
					SourceOp = "Transform1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -715, 214.5 } },
		},
		Merge4_1_3_9 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "ColorCorrector1_2_9",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 1996.5 } },
		},
		LumaKeyer1 = LumaKeyer {
			Inputs = {
				High = Input { Value = 0.9337748, },
				MatteGamma = Input { Value = 0.4421058, },
				Invert = Input { Value = 1, },
				Input = Input {
					SourceOp = "Merge2",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -55, 16.5 } },
		},
		Instance_Transform4_3 = Transform {
			SourceOp = "Transform4",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				TransformNest = Input { },
				ReferenceSize = Input { },
				Input = Input {
					SourceOp = "Merge1_2",
					Source = "Output",
				},
				EffectMask = Input { }
			},
			ViewInfo = OperatorInfo { Pos = { 110, 148.5 } },
		},
		Instance_Crop1_1_1_1 = Crop {
			SourceOp = "Instance_Crop1_2_1_1",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_2_1_1",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 511.5 } },
		},
		Merge4_1_3 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "ColorCorrector1_2",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 346.5 } },
		},
		Saver1_5_10 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/KH.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_4_10",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 2227.5 } },
		},
		Background1_1_2 = Background {
			Inputs = {
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 120, },
				Height = Input { Value = 120, },
				TopLeftAlpha = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -330, 115.5 } },
		},
		Instance_Scale1_1_1_6 = Scale {
			SourceOp = "Instance_Scale1_2_1_6",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_1_1_6",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1336.5 } },
		},
		Background4_1_1 = Background {
			Inputs = {
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 70, },
				Height = Input { Value = 70, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				EffectMask = Input {
					SourceOp = "Ellipse3",
					Source = "Mask",
				}
			},
			ViewInfo = OperatorInfo { Pos = { -550, -379.5 } },
		},
		Transform3 = Transform {
			Inputs = {
				Center = Input { Value = { 0.5, 0.395833333333333 }, },
				Size = Input { Value = 0.771428571428571, },
				Input = Input {
					SourceOp = "Merge7",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -385, -445.5 } },
		},
		Merge3_2_2_6 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2_6",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_2",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.336847437677603 }, },
				Size = Input { Value = 0.949970674486804, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 0, 1402.5 } },
		},
		Saver1_3_1_11 = Saver {
			CtrlWZoom = false,
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/AS.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_1_1_11",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 2326.5 } },
		},
		Instance_Crop1_4_4 = Crop {
			SourceOp = "Instance_Crop1_2_1_4",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_2_4",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1072.5 } },
		},
		Instance_Crop1_3_1_10 = Crop {
			SourceOp = "Instance_Crop1_2_1_10",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_3_10",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 2260.5 } },
		},
		Merge3_2_1_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_1",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.34458438158476 }, },
				Size = Input { Value = 0.961301671064204, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -110, 1534.5 } },
		},
		Polygon3 = PolylineMask {
			DrawMode = "InsertAndModify",
			DrawMode2 = "InsertAndModify",
			Inputs = {
				Filter = Input { Value = FuID { "Fast Gaussian" }, },
				MaskWidth = Input { Value = 1920, },
				MaskHeight = Input { Value = 1080, },
				PixelAspect = Input { Value = { 1, 1 }, },
				ClippingMode = Input { Value = FuID { "None" }, },
				Polyline = Input {
					SourceOp = "Polygon3Polyline",
					Source = "Value",
				},
				Polyline2 = Input {
					Value = Polyline {
					},
					Disabled = true,
				},
			},
			ViewInfo = OperatorInfo { Pos = { -440, 280.5 } },
		},
		Saver1_4_1_9 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/DD.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_3_1_9",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 2095.5 } },
		},
		Instance_Crop1_2_1_5 = Crop {
			Inputs = {
				XOffset = Input { Value = 56, },
				YOffset = Input { Value = 60, },
				XSize = Input { Value = 108, },
				YSize = Input { Value = 180, },
				KeepCentered = Input { Value = 1, },
				Input = Input {
					SourceOp = "Merge3_2_1_1_1_5",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1204.5 } },
		},
		Instance_Scale1_4_8 = Scale {
			SourceOp = "Instance_Scale1_2_1_8",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_4_8",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1897.5 } },
		},
		Background3 = Background {
			Inputs = {
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 400, },
				Height = Input { Value = 34, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				TopLeftRed = Input { Value = 1, },
				TopLeftGreen = Input { Value = 1, },
				TopLeftBlue = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { -385, -544.5 } },
		},
		Instance_Scale1_4 = Scale {
			SourceOp = "Instance_Scale1_2_1",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_4",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 412.5 } },
		},
		Instance_Scale1_3_1_3 = Scale {
			SourceOp = "Instance_Scale1_2_1_3",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_3_1_3",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 940.5 } },
		},
		Saver1_2_1_3 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/5C.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_2_1_3",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 874.5 } },
		},
		Instance_Crop1_2_1 = Crop {
			Inputs = {
				XOffset = Input { Value = 56, },
				YOffset = Input { Value = 60, },
				XSize = Input { Value = 108, },
				YSize = Input { Value = 180, },
				KeepCentered = Input { Value = 1, },
				Input = Input {
					SourceOp = "Merge3_2_1_1_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 220, 379.5 } },
		},
		Instance_Scale1_2_1_2 = Scale {
			Inputs = {
				XSize = Input { Value = 0.3333, },
				HiQOnly = Input { Value = 0, },
				PixelAspect = Input { Value = { 1, 1 }, },
				Input = Input {
					SourceOp = "Instance_Crop1_2_1_2",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 709.5 } },
		},
		Instance_Crop1_1_1_9 = Crop {
			SourceOp = "Instance_Crop1_2_1_9",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_2_1_9",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1996.5 } },
		},
		Instance_Transform4_1 = Transform {
			SourceOp = "Transform4",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				TransformNest = Input { },
				ReferenceSize = Input { },
				Input = Input {
					SourceOp = "Merge1_2_1_1",
					Source = "Output",
				},
				EffectMask = Input { }
			},
			ViewInfo = OperatorInfo { Pos = { -110, 148.5 } },
		},
		ColorCorrector1_2_2 = ColorCorrector {
			Inputs = {
				WheelSaturation1 = Input { Value = 0, },
				MasterRGBGain = Input { Value = 0, },
				ColorRanges = Input {
					Value = ColorCurves {
						Curves = {
							{
								Points = {
									{ 0, 1 },
									{ 0.4, 0.2 },
									{ 0.6, 0 },
									{ 1, 0 }
								}
							},
							{
								Points = {
									{ 0, 0 },
									{ 0.4, 0 },
									{ 0.6, 0.2 },
									{ 1, 1 }
								}
							}
						}
					},
				},
				HistogramIgnoreTransparent = Input { Value = 1, },
				Input = Input {
					SourceOp = "Instance_Transform4_5",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -605, 676.5 } },
		},
		Background3_1 = Background {
			Inputs = {
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 400, },
				Height = Input { Value = 34, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				TopLeftAlpha = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 0, -544.5 } },
		},
		Merge3_2_1_1_1_8 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3_8",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_1",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.34458438158476 }, },
				Size = Input { Value = 0.961301671064204, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -110, 1864.5 } },
		},
		Text1_1_1_8 = TextPlus {
			Inputs = {
				HorizontalJustificationNew = Input { Value = 3, },
				VerticalJustificationNew = Input { Value = 3, },
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				Center = Input { Value = { 0.5, 0.558812988832998 }, },
				Font = Input { Value = "DejaVu Sans", },
				StyledText = Input { Value = "J", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Alignment = Input { Value = 1, },
				HorizontalJustification = Input { Value = 1, },
				Red1 = Input { Value = 0.778792858123779, },
				Green1 = Input { Value = 0.0274509191513062, },
				Blue1 = Input { Value = 0.0961014628410339, },
				EffectMask = Input {
					SourceOp = "Rectangle4",
					Source = "Mask",
				}
			},
			ViewInfo = OperatorInfo { Pos = { -825, 1831.5 } },
		},
		Instance_Scale1_2_1_8 = Scale {
			Inputs = {
				XSize = Input { Value = 0.3333, },
				HiQOnly = Input { Value = 0, },
				PixelAspect = Input { Value = { 1, 1 }, },
				Input = Input {
					SourceOp = "Instance_Crop1_2_1_8",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1864.5 } },
		},
		Background1_1_1 = Background {
			Inputs = {
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 693, },
				Height = Input { Value = 175, },
				TopLeftRed = Input { Value = 0.772549092769623, },
				TopLeftBlue = Input { Value = 0.0705882385373116, },
				EffectMask = Input {
					SourceOp = "LumaKeyer1",
					Source = "Output",
				}
			},
			ViewInfo = OperatorInfo { Pos = { 55, 82.5 } },
		},
		Instance_Crop1_4 = Crop {
			SourceOp = "Instance_Crop1_2_1",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_2",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 412.5 } },
		},
		Saver1_2_1_8 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/JC.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_2_1_8",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1864.5 } },
		},
		Instance_Crop1_4_5 = Crop {
			SourceOp = "Instance_Crop1_2_1_5",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_2_5",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1237.5 } },
		},
		Merge4_1_3_4 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "ColorCorrector1_2_4",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 1006.5 } },
		},
		Text1_1 = TextPlus {
			Inputs = {
				HorizontalJustificationNew = Input { Value = 3, },
				VerticalJustificationNew = Input { Value = 3, },
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				Center = Input { Value = { 0.5, 0.545083011716293 }, },
				Font = Input { Value = "DejaVu Sans", },
				StyledText = Input { Value = "9", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Alignment = Input { Value = 1, },
				HorizontalJustification = Input { Value = 1, },
				Red1 = Input { Value = 0.778792858123779, },
				Green1 = Input { Value = 0.0274509191513062, },
				Blue1 = Input { Value = 0.0961014628410339, },
			},
			ViewInfo = OperatorInfo { Pos = { -825, 1501.5 } },
		},
		Merge3_2_1_2 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.348452853538338 }, },
				Size = Input { Value = 0.864555848724714, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -220, 1501.5 } },
		},
		Instance_Crop1_3_1_9 = Crop {
			SourceOp = "Instance_Crop1_2_1_9",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_3_9",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 2095.5 } },
		},
		Saver1_2_1_10 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/KC.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_2_1_10",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 2194.5 } },
		},
		Saver1_4_1 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/2D.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_3_1",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 445.5 } },
		},
		Merge3_2_1_1_1_6 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3_6",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_1",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.34458438158476 }, },
				Size = Input { Value = 0.961301671064204, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -110, 1369.5 } },
		},
		Instance_Crop1_1_1_3 = Crop {
			SourceOp = "Instance_Crop1_2_1_3",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_2_1_3",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 841.5 } },
		},
		Merge3_2_2_5 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2_5",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_2",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.336847437677603 }, },
				Size = Input { Value = 0.949970674486804, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 0, 1237.5 } },
		},
		Merge4_1_1_2_9 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_13",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 2062.5 } },
		},
		Merge4_1_1_2_8 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_12",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 1897.5 } },
		},
		Saver1_4_1_3 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/5D.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_3_1_3",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 940.5 } },
		},
		Merge3_2_1_2_1_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.348452853538338 }, },
				Size = Input { Value = 0.864555848724714, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -220, 511.5 } },
		},
		Instance_Crop1_3_1_2 = Crop {
			SourceOp = "Instance_Crop1_2_1_2",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_3_2",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 775.5 } },
		},
		Merge3_2_1_3_2 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2_2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_3",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.354255561468705 }, },
				Size = Input { Value = 0.883932231992637, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 110, 775.5 } },
		},
		Merge3_2_1_3 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_3",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.354255561468705 }, },
				Size = Input { Value = 0.883932231992637, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 110, 445.5 } },
		},
		Text1_2 = TextPlus {
			Inputs = {
				HorizontalJustificationNew = Input { Value = 3, },
				VerticalJustificationNew = Input { Value = 3, },
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Center = Input { Value = { 0.499178403755869, 0.505575467941059 }, },
				Size = Input { Value = 0.0302, },
				Font = Input { Value = "Open Sans", },
				StyledText = Input { Value = "AI", },
				Style = Input { Value = "Extrabold Italic", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Green1 = Input { Value = 0.0156862754374743, },
				Blue1 = Input { Value = 0.0156862754374743, },
			},
			ViewInfo = OperatorInfo { Pos = { -165, -412.5 } },
		},
		Instance_Scale1_1_1_11 = Scale {
			SourceOp = "Instance_Scale1_2_1_11",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_1_1_11",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 2326.5 } },
		},
		Instance_Crop1_2_1_7 = Crop {
			Inputs = {
				XOffset = Input { Value = 56, },
				YOffset = Input { Value = 60, },
				XSize = Input { Value = 108, },
				YSize = Input { Value = 180, },
				KeepCentered = Input { Value = 1, },
				Input = Input {
					SourceOp = "Merge3_2_1_1_1_7",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1699.5 } },
		},
		Text1_1_1_3 = TextPlus {
			Inputs = {
				HorizontalJustificationNew = Input { Value = 3, },
				VerticalJustificationNew = Input { Value = 3, },
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				Center = Input { Value = { 0.5, 0.545083011716293 }, },
				Font = Input { Value = "DejaVu Sans", },
				StyledText = Input { Value = "5", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Alignment = Input { Value = 1, },
				HorizontalJustification = Input { Value = 1, },
				Red1 = Input { Value = 0.778792858123779, },
				Green1 = Input { Value = 0.0274509191513062, },
				Blue1 = Input { Value = 0.0961014628410339, },
			},
			ViewInfo = OperatorInfo { Pos = { -825, 841.5 } },
		},
		Merge3_2_2_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_2",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.336847437677603 }, },
				Size = Input { Value = 0.949970674486804, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 0, 577.5 } },
		},
		Instance_Scale1_2_1 = Scale {
			Inputs = {
				XSize = Input { Value = 0.3333, },
				HiQOnly = Input { Value = 0, },
				PixelAspect = Input { Value = { 1, 1 }, },
				Input = Input {
					SourceOp = "Instance_Crop1_2_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 379.5 } },
		},
		Saver1_4_1_8 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/JD.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_3_1_8",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1930.5 } },
		},
		Merge3_2_1_3_11 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2_11",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_3",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.354255561468705 }, },
				Size = Input { Value = 0.883932231992637, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 110, 2425.5 } },
		},
		Merge3_2_1_2_1_10 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3_10",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.348452853538338 }, },
				Size = Input { Value = 0.864555848724714, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -220, 2161.5 } },
		},
		Merge4_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "ColorCorrector1",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 1501.5 } },
		},
		ColorCorrector1_2_3 = ColorCorrector {
			Inputs = {
				WheelSaturation1 = Input { Value = 0, },
				MasterRGBGain = Input { Value = 0, },
				ColorRanges = Input {
					Value = ColorCurves {
						Curves = {
							{
								Points = {
									{ 0, 1 },
									{ 0.4, 0.2 },
									{ 0.6, 0 },
									{ 1, 0 }
								}
							},
							{
								Points = {
									{ 0, 0 },
									{ 0.4, 0 },
									{ 0.6, 0.2 },
									{ 1, 1 }
								}
							}
						}
					},
				},
				HistogramIgnoreTransparent = Input { Value = 1, },
				Input = Input {
					SourceOp = "Instance_Transform4_6",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -605, 841.5 } },
		},
		Merge4_1_3_6 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "ColorCorrector1_2_6",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 1336.5 } },
		},
		Text1_1_1_10 = TextPlus {
			Inputs = {
				HorizontalJustificationNew = Input { Value = 3, },
				VerticalJustificationNew = Input { Value = 3, },
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				Center = Input { Value = { 0.5, 0.545083011716293 }, },
				Font = Input { Value = "DejaVu Sans", },
				StyledText = Input { Value = "K", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Alignment = Input { Value = 1, },
				HorizontalJustification = Input { Value = 1, },
				Red1 = Input { Value = 0.778792858123779, },
				Green1 = Input { Value = 0.0274509191513062, },
				Blue1 = Input { Value = 0.0961014628410339, },
			},
			ViewInfo = OperatorInfo { Pos = { -825, 2161.5 } },
		},
		Merge4_1_1_2_6 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_9",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 1402.5 } },
		},
		Instance_Scale1_4_4 = Scale {
			SourceOp = "Instance_Scale1_2_1_4",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_4_4",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1072.5 } },
		},
		Merge3_2_2_9 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2_9",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_2",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.336847437677603 }, },
				Size = Input { Value = 0.949970674486804, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 0, 2062.5 } },
		},
		Instance_Scale1_1_1_7 = Scale {
			SourceOp = "Instance_Scale1_2_1_7",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_1_1_7",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1666.5 } },
		},
		Instance_Transform4_12 = Transform {
			SourceOp = "Transform4",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				TransformNest = Input { },
				ReferenceSize = Input { },
				Input = Input {
					SourceOp = "Text1_1_1_8",
					Source = "Output",
				},
				EffectMask = Input { }
			},
			ViewInfo = OperatorInfo { Pos = { -715, 1831.5 } },
		},
		Instance_Scale1_1_1_8 = Scale {
			SourceOp = "Instance_Scale1_2_1_8",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_1_1_8",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1831.5 } },
		},
		Instance_Scale1_4_10 = Scale {
			SourceOp = "Instance_Scale1_2_1_10",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_4_10",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 2227.5 } },
		},
		Merge3_2_1_2_1_4 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3_4",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.348452853538338 }, },
				Size = Input { Value = 0.864555848724714, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -220, 1006.5 } },
		},
		Merge4_1_3_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "ColorCorrector1_2_1",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 511.5 } },
		},
		Scale1 = Scale {
			Inputs = {
				XSize = Input { Value = 0.3333, },
				HiQOnly = Input { Value = 0, },
				PixelAspect = Input { Value = { 1, 1 }, },
				Input = Input {
					SourceOp = "Crop1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 214.5 } },
		},
		Merge3_2_2_3 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2_3",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_2",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.336847437677603 }, },
				Size = Input { Value = 0.949970674486804, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 0, 907.5 } },
		},
		Instance_Crop1_3_1_1 = Crop {
			SourceOp = "Instance_Crop1_2_1_1",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_3_1",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 610.5 } },
		},
		Merge1_2_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background1_1_2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Background1_1",
					Source = "Output",
				},
				Center = Input { Value = { 0.668324613462439, 0.231103286384977 }, },
				PerformDepthMerge = Input { Value = 0, },
				EffectMask = Input {
					SourceOp = "Rectangle2",
					Source = "Mask",
				}
			},
			ViewInfo = OperatorInfo { Pos = { -220, 115.5 } },
		},
		Saver1_2_1_1 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/3C.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_2_1_1",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 544.5 } },
		},
		Instance_Scale1_2_1_3 = Scale {
			Inputs = {
				XSize = Input { Value = 0.3333, },
				HiQOnly = Input { Value = 0, },
				PixelAspect = Input { Value = { 1, 1 }, },
				Input = Input {
					SourceOp = "Instance_Crop1_2_1_3",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 874.5 } },
		},
		Saver1_5_2 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/4H.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_4_2",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 742.5 } },
		},
		Instance_Scale1_4_5 = Scale {
			SourceOp = "Instance_Scale1_2_1_5",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_4_5",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1237.5 } },
		},
		Transform1 = Transform {
			Inputs = {
				Center = Input { Value = { 0.8742804276316, 0.493 }, },
				Input = Input {
					SourceOp = "Loader2",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -825, 214.5 } },
		},
		Instance_Scale1_3_1_1 = Scale {
			SourceOp = "Instance_Scale1_2_1_1",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_3_1_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 610.5 } },
		},
		Text1_1_1_11 = TextPlus {
			Inputs = {
				HorizontalJustificationNew = Input { Value = 3, },
				VerticalJustificationNew = Input { Value = 3, },
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				Center = Input { Value = { 0.5, 0.545083011716293 }, },
				Font = Input { Value = "DejaVu Sans", },
				StyledText = Input { Value = "A", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Alignment = Input { Value = 1, },
				HorizontalJustification = Input { Value = 1, },
				Red1 = Input { Value = 0.778792858123779, },
				Green1 = Input { Value = 0.0274509191513062, },
				Blue1 = Input { Value = 0.0961014628410339, },
			},
			ViewInfo = OperatorInfo { Pos = { -825, 2326.5 } },
		},
		ColorCorrector1_2_8 = ColorCorrector {
			Inputs = {
				WheelSaturation1 = Input { Value = 0, },
				MasterRGBGain = Input { Value = 0, },
				ColorRanges = Input {
					Value = ColorCurves {
						Curves = {
							{
								Points = {
									{ 0, 1 },
									{ 0.4, 0.2 },
									{ 0.6, 0 },
									{ 1, 0 }
								}
							},
							{
								Points = {
									{ 0, 0 },
									{ 0.4, 0 },
									{ 0.6, 0.2 },
									{ 1, 1 }
								}
							}
						}
					},
				},
				HistogramIgnoreTransparent = Input { Value = 1, },
				Input = Input {
					SourceOp = "Instance_Transform4_12",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -605, 1831.5 } },
		},
		Merge3_2_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_3",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.354255561468705 }, },
				Size = Input { Value = 0.883932231992637, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 110, 1600.5 } },
		},
		Saver1_5_9 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/DH.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_4_9",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 2062.5 } },
		},
		Rectangle1 = RectangleMask {
			Inputs = {
				MaskWidth = Input { Value = 1920, },
				MaskHeight = Input { Value = 1080, },
				PixelAspect = Input { Value = { 1, 1 }, },
				ClippingMode = Input { Value = FuID { "None" }, },
				Width = Input { Value = 0.485870689564178, },
				Height = Input { Value = 0.597786850875861, },
				CornerRadius = Input { Value = 0.346, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 82.5 } },
		},
		Instance_Scale1_3_1_5 = Scale {
			SourceOp = "Instance_Scale1_2_1_5",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_3_1_5",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1270.5 } },
		},
		Merge3_2_1_3_8 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2_8",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_3",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.354255561468705 }, },
				Size = Input { Value = 0.883932231992637, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 110, 1930.5 } },
		},
		Polygon5 = PolylineMask {
			DrawMode = "InsertAndModify",
			DrawMode2 = "InsertAndModify",
			Inputs = {
				Filter = Input { Value = FuID { "Fast Gaussian" }, },
				MaskWidth = Input { Value = 1920, },
				MaskHeight = Input { Value = 1080, },
				PixelAspect = Input { Value = { 1, 1 }, },
				ClippingMode = Input { Value = FuID { "None" }, },
				Polyline = Input {
					SourceOp = "Polygon5Polyline",
					Source = "Value",
				},
				Polyline2 = Input {
					Value = Polyline {
					},
					Disabled = true,
				},
			},
			ViewInfo = OperatorInfo { Pos = { -55, -346.5 } },
		},
		Merge4_1_3_8 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "ColorCorrector1_2_8",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 1831.5 } },
		},
		Instance_Scale1_2_1_10 = Scale {
			Inputs = {
				XSize = Input { Value = 0.3333, },
				HiQOnly = Input { Value = 0, },
				PixelAspect = Input { Value = { 1, 1 }, },
				Input = Input {
					SourceOp = "Instance_Crop1_2_1_10",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 2194.5 } },
		},
		Instance_Crop1_1_1_2 = Crop {
			SourceOp = "Instance_Crop1_2_1_2",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_2_1_2",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 676.5 } },
		},
		Saver1_4_1_10 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/KD.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_3_1_10",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 2260.5 } },
		},
		Merge4_1_1_2_10 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_14",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 2227.5 } },
		},
		Instance_Scale1_2 = Scale {
			SourceOp = "Scale1",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_2",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1534.5 } },
		},
		Text1_1_1_1 = TextPlus {
			Inputs = {
				HorizontalJustificationNew = Input { Value = 3, },
				VerticalJustificationNew = Input { Value = 3, },
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				Center = Input { Value = { 0.5, 0.545083011716293 }, },
				Font = Input { Value = "DejaVu Sans", },
				StyledText = Input { Value = "3", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Alignment = Input { Value = 1, },
				HorizontalJustification = Input { Value = 1, },
				Red1 = Input { Value = 0.778792858123779, },
				Green1 = Input { Value = 0.0274509191513062, },
				Blue1 = Input { Value = 0.0961014628410339, },
			},
			ViewInfo = OperatorInfo { Pos = { -825, 511.5 } },
		},
		Instance_Crop1_4_9 = Crop {
			SourceOp = "Instance_Crop1_2_1_9",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_2_9",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 2062.5 } },
		},
		Text1_1_1_6 = TextPlus {
			Inputs = {
				HorizontalJustificationNew = Input { Value = 3, },
				VerticalJustificationNew = Input { Value = 3, },
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				Center = Input { Value = { 0.5, 0.545083011716293 }, },
				Font = Input { Value = "DejaVu Sans", },
				StyledText = Input { Value = "8", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Alignment = Input { Value = 1, },
				HorizontalJustification = Input { Value = 1, },
				Red1 = Input { Value = 0.778792858123779, },
				Green1 = Input { Value = 0.0274509191513062, },
				Blue1 = Input { Value = 0.0961014628410339, },
			},
			ViewInfo = OperatorInfo { Pos = { -825, 1336.5 } },
		},
		Transform4 = Transform {
			Inputs = {
				Size = Input { Value = 0.89634765625, },
				Input = Input {
					SourceOp = "Text1_1_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -715, 346.5 } },
		},
		Text1_1_1 = TextPlus {
			Inputs = {
				HorizontalJustificationNew = Input { Value = 3, },
				VerticalJustificationNew = Input { Value = 3, },
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				Center = Input { Value = { 0.5, 0.545083011716293 }, },
				Font = Input { Value = "DejaVu Sans", },
				StyledText = Input { Value = "2", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Alignment = Input { Value = 1, },
				HorizontalJustification = Input { Value = 1, },
				Red1 = Input { Value = 0.778792858123779, },
				Green1 = Input { Value = 0.0274509191513062, },
				Blue1 = Input { Value = 0.0961014628410339, },
			},
			ViewInfo = OperatorInfo { Pos = { -825, 346.5 } },
		},
		Merge4_1_1_2_3 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_6",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 907.5 } },
		},
		Instance_Crop1_3_1_6 = Crop {
			SourceOp = "Instance_Crop1_2_1_6",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_3_6",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1435.5 } },
		},
		Saver1_4_1_11 = Saver {
			CtrlWZoom = false,
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/AD.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_3_1_11",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 2425.5 } },
		},
		Instance_Scale1_3_1_6 = Scale {
			SourceOp = "Instance_Scale1_2_1_6",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_3_1_6",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1435.5 } },
		},
		Merge9 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge8",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Text1_2",
					Source = "Output",
				},
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -165, -379.5 } },
		},
		Merge3_2_1_3_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_3",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.354255561468705 }, },
				Size = Input { Value = 0.883932231992637, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 110, 610.5 } },
		},
		Instance_Crop1_4_8 = Crop {
			SourceOp = "Instance_Crop1_2_1_8",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_2_8",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1897.5 } },
		},
		Instance_Crop1_4_6 = Crop {
			SourceOp = "Instance_Crop1_2_1_6",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_2_6",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1402.5 } },
		},
		ColorCorrector1_2_5 = ColorCorrector {
			Inputs = {
				WheelSaturation1 = Input { Value = 0, },
				MasterRGBGain = Input { Value = 0, },
				ColorRanges = Input {
					Value = ColorCurves {
						Curves = {
							{
								Points = {
									{ 0, 1 },
									{ 0.4, 0.2 },
									{ 0.6, 0 },
									{ 1, 0 }
								}
							},
							{
								Points = {
									{ 0, 0 },
									{ 0.4, 0 },
									{ 0.6, 0.2 },
									{ 1, 1 }
								}
							}
						}
					},
				},
				HistogramIgnoreTransparent = Input { Value = 1, },
				Input = Input {
					SourceOp = "Instance_Transform4_8",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -605, 1171.5 } },
		},
		Saver1_2_1_9 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/DC.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_2_1_9",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 2029.5 } },
		},
		ColorCorrector1_2 = ColorCorrector {
			Inputs = {
				WheelSaturation1 = Input { Value = 0, },
				MasterRGBGain = Input { Value = 0, },
				ColorRanges = Input {
					Value = ColorCurves {
						Curves = {
							{
								Points = {
									{ 0, 1 },
									{ 0.4, 0.2 },
									{ 0.6, 0 },
									{ 1, 0 }
								}
							},
							{
								Points = {
									{ 0, 0 },
									{ 0.4, 0 },
									{ 0.6, 0.2 },
									{ 1, 1 }
								}
							}
						}
					},
				},
				HistogramIgnoreTransparent = Input { Value = 1, },
				Input = Input {
					SourceOp = "Transform4",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -605, 346.5 } },
		},
		Saver1_5_5 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/7H.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_4_5",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1237.5 } },
		},
		Instance_Crop1_4_10 = Crop {
			SourceOp = "Instance_Crop1_2_1_10",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_2_10",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 2227.5 } },
		},
		Merge3_2_1_3_6 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2_6",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_3",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.354255561468705 }, },
				Size = Input { Value = 0.883932231992637, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 110, 1435.5 } },
		},
		Merge3_2_1_1_1_1 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_1",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.34458438158476 }, },
				Size = Input { Value = 0.961301671064204, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -110, 544.5 } },
		},
		Instance_Crop1_1 = Crop {
			SourceOp = "Crop1",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_2",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1501.5 } },
		},
		Instance_Crop1_3_1_8 = Crop {
			SourceOp = "Instance_Crop1_2_1_8",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_3_8",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1930.5 } },
		},
		Polygon4 = PolylineMask {
			DrawMode = "InsertAndModify",
			DrawMode2 = "InsertAndModify",
			Inputs = {
				Filter = Input { Value = FuID { "Fast Gaussian" }, },
				MaskWidth = Input { Value = 1920, },
				MaskHeight = Input { Value = 1080, },
				PixelAspect = Input { Value = { 1, 1 }, },
				ClippingMode = Input { Value = FuID { "None" }, },
				Polyline = Input {
					SourceOp = "Polygon4Polyline",
					Source = "Value",
				},
				Polyline2 = Input {
					Value = Polyline {
					},
					Disabled = true,
				},
			},
			ViewInfo = OperatorInfo { Pos = { -385, 181.5 } },
		},
		Instance_Crop1_1_1_8 = Crop {
			SourceOp = "Instance_Crop1_2_1_8",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_2_1_8",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1831.5 } },
		},
		Instance_Transform4_15 = Transform {
			SourceOp = "Transform4",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				TransformNest = Input { },
				ReferenceSize = Input { },
				Input = Input {
					SourceOp = "Text1_1_1_11",
					Source = "Output",
				},
				EffectMask = Input { }
			},
			ViewInfo = OperatorInfo { Pos = { -715, 2326.5 } },
		},
		Instance_Scale1_1_1_1 = Scale {
			SourceOp = "Instance_Scale1_2_1_1",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_1_1_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 511.5 } },
		},
		ColorCorrector1_2_7 = ColorCorrector {
			Inputs = {
				WheelSaturation1 = Input { Value = 0, },
				MasterRGBGain = Input { Value = 0, },
				ColorRanges = Input {
					Value = ColorCurves {
						Curves = {
							{
								Points = {
									{ 0, 1 },
									{ 0.4, 0.2 },
									{ 0.6, 0 },
									{ 1, 0 }
								}
							},
							{
								Points = {
									{ 0, 0 },
									{ 0.4, 0 },
									{ 0.6, 0.2 },
									{ 1, 1 }
								}
							}
						}
					},
				},
				HistogramIgnoreTransparent = Input { Value = 1, },
				Input = Input {
					SourceOp = "Instance_Transform4_11",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -605, 1666.5 } },
		},
		Instance_Crop1_4_2 = Crop {
			SourceOp = "Instance_Crop1_2_1_2",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_2_2",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 742.5 } },
		},
		Instance_Scale1_1 = Scale {
			SourceOp = "Scale1",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1501.5 } },
		},
		Instance_Scale1_2_1_9 = Scale {
			Inputs = {
				XSize = Input { Value = 0.3333, },
				HiQOnly = Input { Value = 0, },
				PixelAspect = Input { Value = { 1, 1 }, },
				Input = Input {
					SourceOp = "Instance_Crop1_2_1_9",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 2029.5 } },
		},
		Merge3_2_1_3_4 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_1_2_4",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_3",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.354255561468705 }, },
				Size = Input { Value = 0.883932231992637, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 110, 1105.5 } },
		},
		Instance_Scale1_3_1 = Scale {
			SourceOp = "Instance_Scale1_2_1",
			Inputs = {
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				FrameRenderScriptNest = Input { },
				CommentsNest = Input { },
				Input = Input {
					SourceOp = "Instance_Crop1_3_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 445.5 } },
		},
		Instance_Crop1_4_3 = Crop {
			SourceOp = "Instance_Crop1_2_1_3",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_2_3",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 907.5 } },
		},
		Merge4_1_1_2_2 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_5",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 742.5 } },
		},
		Merge7 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background4_1_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader4",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.448598130841121 }, },
				Size = Input { Value = 0.084, },
				PerformDepthMerge = Input { Value = 0, },
				EffectMask = Input {
					SourceOp = "Ellipse3_1",
					Source = "Mask",
				}
			},
			ViewInfo = OperatorInfo { Pos = { -440, -379.5 } },
		},
		Saver1_2_1 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/2C.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_2_1",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 379.5 } },
		},
		Merge3_2_1_1_1_10 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3_10",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_1",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.34458438158476 }, },
				Size = Input { Value = 0.961301671064204, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -110, 2194.5 } },
		},
		Merge4_1_1_2_5 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_8",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 1237.5 } },
		},
		Saver1_3 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/9S.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_1",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1501.5 } },
		},
		Instance_Crop1_3_1_5 = Crop {
			SourceOp = "Instance_Crop1_2_1_5",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_3_5",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1270.5 } },
		},
		Saver1_4_1_5 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/7D.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_3_1_5",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1270.5 } },
		},
		Instance_Transform4_5 = Transform {
			SourceOp = "Transform4",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				TransformNest = Input { },
				ReferenceSize = Input { },
				Input = Input {
					SourceOp = "Text1_1_1_2",
					Source = "Output",
				},
				EffectMask = Input { }
			},
			ViewInfo = OperatorInfo { Pos = { -715, 676.5 } },
		},
		Background1 = Background {
			Inputs = {
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				TopLeftRed = Input { Value = 1, },
				TopLeftGreen = Input { Value = 1, },
				TopLeftBlue = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 55, -16.5 } },
		},
		Instance_Transform4_4 = Transform {
			SourceOp = "Transform4",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				TransformNest = Input { },
				ReferenceSize = Input { },
				Input = Input {
					SourceOp = "Text1_1_1_1",
					Source = "Output",
				},
				EffectMask = Input { }
			},
			ViewInfo = OperatorInfo { Pos = { -715, 511.5 } },
		},
		Text1_1_1_7 = TextPlus {
			Inputs = {
				HorizontalJustificationNew = Input { Value = 3, },
				VerticalJustificationNew = Input { Value = 3, },
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				Center = Input { Value = { 0.5, 0.545083011716293 }, },
				Font = Input { Value = "DejaVu Sans", },
				StyledText = Input { Value = "T", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				Alignment = Input { Value = 1, },
				HorizontalJustification = Input { Value = 1, },
				Red1 = Input { Value = 0.778792858123779, },
				Green1 = Input { Value = 0.0274509191513062, },
				Blue1 = Input { Value = 0.0961014628410339, },
			},
			ViewInfo = OperatorInfo { Pos = { -825, 1666.5 } },
		},
		Merge4_1_3_7 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "ColorCorrector1_2_7",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 1666.5 } },
		},
		Instance_Crop1_1_1_4 = Crop {
			SourceOp = "Instance_Crop1_2_1_4",
			Inputs = {
				CommentsNest = Input { },
				FrameRenderScriptNest = Input { },
				StartRenderScripts = Input { },
				SettingsNest = Input { },
				EndRenderScripts = Input { },
				ResetSize = Input { },
				ResetOffset = Input { },
				Input = Input {
					SourceOp = "Merge3_2_1_2_1_4",
					Source = "Output",
				},
				AutoCrop = Input { },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 1006.5 } },
		},
		Instance_Scale1_2_1_7 = Scale {
			Inputs = {
				XSize = Input { Value = 0.3333, },
				HiQOnly = Input { Value = 0, },
				PixelAspect = Input { Value = { 1, 1 }, },
				Input = Input {
					SourceOp = "Instance_Crop1_2_1_7",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 330, 1699.5 } },
		},
		Merge4 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Transform2",
					Source = "Output",
				},
				PerformDepthMerge = Input { Value = 0, },
				EffectMask = Input {
					SourceOp = "Polygon3",
					Source = "Mask",
				}
			},
			ViewInfo = OperatorInfo { Pos = { -495, 247.5 } },
		},
		Transform2 = Transform {
			Inputs = {
				Size = Input { Value = 0.122, },
				Edges = Input { Value = 1, },
				Input = Input {
					SourceOp = "Crop2",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -605, 214.5 } },
		},
		Merge3_2_1_1_1_11 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3_11",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_1",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.34458438158476 }, },
				Size = Input { Value = 0.961301671064204, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -110, 2359.5 } },
		},
		Merge4_1_3_11 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Background2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "ColorCorrector1_2_11",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.490328820116054 }, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -495, 2326.5 } },
		},
		Rectangle2 = RectangleMask {
			Inputs = {
				MaskWidth = Input { Value = 1920, },
				MaskHeight = Input { Value = 1080, },
				PixelAspect = Input { Value = { 1, 1 }, },
				ClippingMode = Input { Value = FuID { "None" }, },
				Width = Input { Value = 1, },
				Height = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 220, 115.5 } },
		},
		Ellipse1 = EllipseMask {
			Inputs = {
				Filter = Input { Value = FuID { "Fast Gaussian" }, },
				MaskWidth = Input { Value = 1920, },
				MaskHeight = Input { Value = 1080, },
				PixelAspect = Input { Value = { 1, 1 }, },
				ClippingMode = Input { Value = FuID { "None" }, },
				Center = Input { Value = { 0.110248464035428, 0.5 }, },
				Width = Input { Value = 0.208018684534568, },
				Height = Input { Value = 0.208018684534568, },
			},
			ViewInfo = OperatorInfo { Pos = { -330, -280.5 } },
		},
		Saver1 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/9H.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 1567.5 } },
		},
		Merge3_2_1_1_1_2 = Merge {
			Inputs = {
				Background = Input {
					SourceOp = "Merge4_1_3_2",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Instance_Transform4_1",
					Source = "Output",
				},
				Center = Input { Value = { 0.5, 0.34458438158476 }, },
				Size = Input { Value = 0.961301671064204, },
				FilterMethod = Input { Value = 5, },
				PerformDepthMerge = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { -110, 709.5 } },
		},
		Saver1_2_1_11 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "/home/pp/projects/pypoks/gui/cards/dfR/AC.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "Instance_Scale1_2_1_11",
					Source = "Output",
				},
				["PNGFormat.PreDivide"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 2359.5 } },
		},
		Background3_1_1 = Background {
			Inputs = {
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 400, },
				Height = Input { Value = 34, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				TopLeftRed = Input { Value = 1, },
				TopLeftGreen = Input { Value = 1, },
				TopLeftBlue = Input { Value = 1, },
				TopLeftAlpha = Input { Value = 0, },
			},
			ViewInfo = OperatorInfo { Pos = { 275, -544.5 } },
		},
		Instance_Merge11_1 = Merge {
			SourceOp = "Merge11_1",
			Inputs = {
				Background = Input {
					SourceOp = "Background3_1_1",
					Source = "Output",
				},
				Foreground = Input {
					SourceOp = "Loader7",
					Source = "Output",
				},
				ReferenceSize = Input { },
				StartEndRenderScripts = Input { },
				EffectMask = Input { }
			},
			ViewInfo = OperatorInfo { Pos = { 385, -544.5 } },
		}
	},
	Views = {
		{
			FrameTypeID = "ChildFrame",
			Mode = 3,
			LayoutPreset = 0,
			Left = 0,
			Top = 27,
			Width = 2560,
			Height = 1227,
			Views = ordered() {
				Main = MultiView {
					Active = "Flow",
					ViewList = ordered() {
						Flow = "FlowView",
						Console = "ConsoleView",
						Timeline = "TimelineView",
						Spline = "SplineEditorView",
						Info = "InfoView",
						Chat = "ChatView"
					},
					Flow = FlowView {
						Flags = {
							Navigator = true,
							AutoHideNavigator = true,
							GridSnap = true,
							AutoSnap = true,
							RemoveRouters = true
						},
						NavigatorSize = { 200, 140 },
						Direction = "Horizontal",
						PipeStyle = "Direct",
						Scale = 1,
						Offset = { 1228, 772 }
					},
					Timeline = TimelineView {
						TreeControlState = {
						},
						DisplayMode = "All Tools",
						ShowCurrentTimeTools = false,
						Filter = "Show All",
						ShowSelectedTools = false,
						ShowAnimatedToolsOnly = false,
						ShowEditBoxes = false,
						KeyFrameView = {
							Position = { Left = 150, Bottom = 343 },
							ScaleX = 0.00214424951267057,
							OffsetX = -0.0514619883040936,
							OffsetY = 0,
							AutoScaling = "scroll",
							AutoSnapTo = "frame",
							AutoSnapToGuidelines = false,
							GuidelinesGrabEnabled = true,
							GuidelinesSnapTo = "frame"
						},
						Spreadsheet = { LeftPos = 150, Visible = false }
					},
					Spline = SplineEditorView {
						LeftPos = 256,
						ScaleX = 0.2,
						ScaleY = 0.00338983050847458,
						OffsetX = -4,
						OffsetY = 0,
						AutoScaling = "scroll",
						AutoSnapTo = "frame",
						AutoSnapToGuidelines = false,
						GuidelinesSnapTo = "frame",
						ShowKeyMarkers = false,
						IndependentHandles = false,
						ShowNonSplineModifiers = false,
						GuidelinesGrabEnabled = true,
						ShowOneToolOnly = false,
						ShowSelectedTools = false,
						ShowAllInputs = false,
						Filter = "Show All"
					},
				},
				Controls = MultiView {
					Active = "Tools",
					ViewList = ordered() {
						Tools = "ControlView",
						Modifiers = "ModifierView"
					},
				},
				Left = "PreviewContainer",
				Right = "PreviewContainer",
				Transport = "TransportView",
				Time = "TimeView"
			},
			Layout = {
				Columns = 2,
				RatioX = 1,
				RatioY = 1,
				{
					Rows = 3,
					RatioX = 0.865362035225049,
					RatioY = 0.00979591836734694,
					{
						Columns = 2,
						RatioX = 1,
						RatioY = 0.4766201804758,
						{ ID = "Left", RatioX = 0.5, RatioY = 0.0103270223752151, Pop = true },
						{ ID = "Right", RatioX = 0.5, Pop = true },
						Pop = true
					},
					{ ID = "Main", RatioY = 0.475799835931091, Pop = true },
					{ ID = "Time", SnapY = 56, Flat = true }
				},
				{
					Rows = 2,
					PixelX = 342,
					{ ID = "Controls", RatioX = 1, RatioY = 1 },
					{ ID = "Transport", FixedY = -2 }
				}
			}
		}
	},
	Prefs = {
		Comp = {
			Interactive = {
				Proxy = {
					Auto = false
				},
			},
			Views = {
				Right = {
					Viewer = {
						ScaleMode = 0,
						Channel = 4294967295,
					},
				},
				Left = {
					Viewer = {
						ScaleMode = 0,
						Channel = 4294967295,
					},
					Guides = {
						Show = false,
					},
				},
				View1 = {
					PickH = 1,
					PickW = 1,
				},
				Defaults = {
					View3D = {
						CamPersp = {
							Separation = 0.1
						},
					},
				},
				RightView = {
					PickH = 1,
					Guides = {
						Show = false
					},
					PickW = 1,
					Viewer = {
						ScaleMode = 0
					}
				},
				View2 = {
					PickW = 1,
					PickH = 1
				},
				LeftView = {
					PickH = 1,
					Guides = {
						Show = false
					},
					PickW = 1,
					Viewer = {
						ScaleMode = 0
					}
				}
			},
			FrameFormat = {
				Rate = 25,
				GuideRatio = 1.77777777777778,
				DepthFull = 3,
				DepthPreview = 3,
				DepthInteractive = 3,
			},
			LastFile = "R:\\DeA Turtles\\_DFren\\turtlesSquad\\turtlesSquad",
			PolyKeyListDlg = {
				Window = {
					Left = 1227,
					Top = 398
				}
			},
			Unsorted = {
				GlobalEnd = 1,
				RenderSettings = {
					Configs = {
						Preview = {
							StepRender = false,
							PriorityClasses = "all",
							CustomAspect = true,
							StepSize = 5,
							SizeType = 1,
							CustomHeight = 160,
							ShowSlaves = false,
							CustomWidth = 200,
							MotionBlur = true,
							UpdateMode = "Some",
							UseNetwork = false,
							Quality = true
						},
						Final = {
							StepRender = false,
							PriorityClasses = "all",
							CustomAspect = true,
							StepSize = 5,
							SizeType = 1,
							CustomHeight = 160,
							ShowSlaves = false,
							CustomWidth = 200,
							MotionBlur = true,
							UpdateMode = "Some",
							UseNetwork = false,
							Quality = true
						}
					},
					PreviewConfig = "Preview",
					CurrentConfig = "Final"
				}
			},
			Paths = {
			},
			FlowView = {
				GridSnap = true,
			},
			QuickTime = {
			},
		}
	}
}

 